### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by snarfed** [microformats/mf2py#79]
on https://www.wihel.de/keine-lieder-ueber-liebe/ . mf2py 1.0.5, python 3.6, lxml.

```
>>> mf2py.parse(url='https://www.wihel.de/keine-lieder-ueber-liebe/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 39, in parse
    return Parser(doc, url, html_parser).to_dict()
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 112, in __init__
    self.parse()
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 365, in parse
    parse_rels(el)
  File "/Users/ryan/src/indie-map/bigquery/local/lib/python3.6/site-packages/mf2py/parser.py", line 299, in parse_rels
    url = text_type(urljoin(self.__url__, el.get('href', '')))
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 482, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 358, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/parse.py", line 408, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by snarfed** [comment]
fixed at head, probably in 1.1.1 or earlier.

**Comment by sknebel** [comment]
Can still reproduce:
```python
>>> a=Parser("<a class='h-card' href='https://[dfdsdfsdf'>dfsfdds</a>",url="https://example.com/")
Traceback (most recent call last):
  File "<pyshell#75>", line 1, in <module>
    a=Parser("<a class='h-card' href='https://[dfdsdfsdf'>dfsfdds</a>",url="https://example.com/")
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 144, in __init__
    if self.__doc__ is not None:
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 437, in parse
    # parse child tags
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 433, in parse_el
    if potential_microformats:
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 433, in parse_el
    if potential_microformats:
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 433, in parse_el
    if potential_microformats:
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 422, in parse_el
  File "C:\code\mf2py\removedeepcopy\mf2py\parser.py", line 200, in handle_microformat
    # stop implied url if any u-* or h-* is already found
  File "C:\code\mf2py\removedeepcopy\mf2py\implied_properties.py", line 177, in url
    return text_type(urljoin(base_url, prop_value))
  File "C:\Users\sknebel\AppData\Local\Programs\Python\Python36-32\lib\urllib\parse.py", line 482, in urljoin
    urlparse(url, bscheme, allow_fragments)
  File "C:\Users\sknebel\AppData\Local\Programs\Python\Python36-32\lib\urllib\parse.py", line 358, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "C:\Users\sknebel\AppData\Local\Programs\Python\Python36-32\lib\urllib\parse.py", line 431, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL```

**Comment by snarfed** [comment]
huh, odd. it works fine for me, both python 2 and 3, both on master and with #121.

```
>>> import mf2py
>>> mf2py.parse("<a class='h-card' href='https://[dfdsdfsdf'>dfsfdds</a>")
{'items': [{'type': ['h-card'], 'properties': {'name': ['dfsfdds'], 'url': ['https://[dfdsdfsdf']}}], 'rels': {}, 'rel-urls': {}, 'debug': {'description': 'mf2py - microformats2 parser for python', 'source': 'https://github.com/microformats/mf2py', 'version': '1.1.1', 'markup parser': 'html5lib'}}
```

**Comment by snarfed** [comment]
...aha, never mind. it crashes when i include `, url="https://example.com/"`.
